baseURL = ""
languageCode = "en-us"
title = "子舒的博客"
theme = "meteor"  
paginate = 7
hasCJKLanguage = true
summaryLength = 99999

[markup]
  [markup.tableOfContents]  # 文章目录
    endLevel = 3
    ordered = false
  [markup.highlight]
    style ="github"    # 高亮风格
    lineNos = false         # 是否显示行号
  [markup.goldmark]         # 是否在md文件中渲染html代码
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  title = "zishu.me"
  logo = "https://imgurl.zishu.me/author.png"
  author = "子舒"
  favicon = "https://imgurl.zishu.me/favicon2.png"
  buildDate = "2020-06-14"

[permalinks]
  blog = "/blog/:slug.html/"

[[params.socials]]
name = "归档"
link = "/blog/"

[[params.socials]]
name = "关于"
link = "/about/"

[[params.socials]]
name = "Search"
link = "/search/"

[[params.socials]]
name = "RSS"
link = "/index.xml"
