baseURL = ""
languageCode = "en-us"
title = "子舒的博客"
theme = "meteor"  
paginate = 7
hasCJKLanguage = true
summaryLength = 99999

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  title = "zishu.me"
  logo = "https://imgurl.zishu.me/author.png"
  author = "子舒"
  favicon = "https://imgurl.zishu.me/favicon2.png"
  buildDate = "2020-06-14"
  twikooID = ""

[permalinks]
  blog = "/blog/:slug.html/"

[[params.socials]]
name = "Home"
link = "/"

[[params.socials]]
name = "Posts"
link = "/blog/"

[[params.socials]]
name = "Message"
link = "/message/"

[[params.socials]]
name = "About"
link = "/about/"

[[params.socials]]
name = "Search"
link = "/search/"
